import { Com } from './comclass';

export const Comdata: Com[] = [
  {
    cname: 'A-ADM-1007',
    username: 'user1',
    displayname: 'Display Name 1',
    ramsize: 6,
    cpu: 'Intel Core',
    ip: ' XXX.XXX.XXX.XX',
    manu: 'Hewlett-Packard',
    model: 'p7-1380t',
    serial: '2MDXXXXXXX',
    drive: 0,
  },
  {
    cname: 'A-ADM-1016',
    username: 'user2',
    displayname: 'Display Name 2',
    ramsize: 6,
    cpu: 'Intel Core',
    ip: ' XXX.XXX.XXX.XX',
    manu: 'Hewlett-Packard',
    model: 'p7-1420t',
    serial: '2MDXXXXXXX',
    drive: 932,
  },
  {
    cname: 'A-ADM-1018',
    username: 'user3',
    displayname: 'Display Name 3',
    ramsize: 6,
    cpu: 'Intel Core',
    ip: ' XXX.XXX.XXX.XX',
    manu: 'Hewlett-Packard',
    model: 'p7-1420t',
    serial: '2MDXXXXXXX',
    drive: 0,
  },
  {
    cname: 'A-ADM-1019',
    username: 'user4',
    displayname: 'Display Name 4',
    ramsize: 6,
    cpu: 'Intel Core',
    ip: ' XXX.XXX.XXX.XX',
    manu: 'Hewlett-Packard',
    model: 'p7-1420t',
    serial: '2MDXXXXXXX',
    drive: 932,
  },
  {
    cname: 'A-ADM-1021',
    username: 'user5',
    displayname: 'Display Name 5',
    ramsize: 6,
    cpu: 'Intel Core',
    ip: ' XXX.XXX.XXX.XX',
    manu: 'Hewlett-Packard',
    model: 'p7-1420t',
    serial: '2MDXXXXXXX',
    drive: 0,
  },
  {
    cname: 'A-ADM-1030',
    username: 'user6',
    displayname: 'Display Name 6',
    ramsize: 4,
    cpu: 'Intel Core',
    ip: ' XXX.XXX.XXX.XX',
    manu: 'Hewlett-Packard',
    model: 'HD Pro3500 Series',
    serial: 'MXLXXXXXXX',
    drive: 466,
  }
];
