import {Ticket} from './ticketclass';

export const Ticketdata: Ticket[] = [
  {
    ticketN: 7066,
    createdBy: 'user1',
    summary: 'More than one AntiVirus is installed on a-adm-1018 (Central Server)',
    descr: ['This ticket was created automatically for alert 19390'],
    status: 'closed',
    category: 'Software - Other',
    department: 'AMD',
    assign: 'Ellery Barnes',
    createDate: '2016-07-01 @ 02:25 AM',
    closeDate: '2016-07-01 @ 01:29 PM',
    priority: 'Med'
  },
  {
    ticketN: 7067,
    createdBy: 'user2',
    summary: 'laptop for Leah Clawson',
    descr: [
    'Earlier this week I provided Ryan with eIDs for the new ARs so',
    'slice he could set each up as an administrator on their respective laptops.',
    'I have since learned that Leah Clawson changed her eID to lclawson (previously lkimzey).',
    'If someone can make that change on Leahs laptop to prevent problems with logging into the ',
    'computer on her first day, it will be greatly appreciated Thanks! Sonia Topliff Executive ',
    'Assistant Office of the Vice President for Student Life Kansas State University 122 ',
    'Anderson Hall 919 Mid-Campus Dr North Manhattan, KS 66506 785.532.6237 ',
    'Deliberative . Developer . Empathy . Harmony . Input', ] ,
    status: 'closed',
    category: 'General',
    department: 'NSS',
    assign: 'James Barnes',
    createDate: '2016-07-01 @ 08:10 AM',
    closeDate: '2016-07-01 @ 08:29 AM',
    priority: 'Med'
  },
  {
    ticketN: 7068,
    createdBy: 'user3',
    summary: 'ARs',
    descr: ['"Someone needs to get to the Welcome Center today to fix these items before staff start next Tuesday',
    'Maya ‰ÛÒ Wireless Keyboard/mouse',
    'Carlos ‰ÛÒ Laptop imaged',
    'Jenny Cooper/Vacant ‰ÛÒ Docking station setup & Wireless Keyboard Mouse',
    'Dr. Lehning ‰ÛÒ Power strip on floor install longer cords',
    'Clean up all wiring in the AR area. Use Velcro straps to combine the wires.',
    'Move network cords out of the paths of the feet and chairs.',
    'Jim Barnes',
    'Information Technology Manager',
    'Student Life Technology & Information Services',
    'Kansas State University',
    'Anderson Hall Room 09',
    'Phone:785-532-2937',
    'Fax:785-532-5477',
    'Email:jbarn@ksu.edu"',
    ],
    status: 'closed',
    category: 'Hardware',
    department: 'NSS',
    assign: 'Ellery Barnes',
    createDate: '2016-07-01 @ 09:29 AM',
    closeDate: '2016-07-01 @ 11:52 AM',
    priority: 'Med'
  },
  {
    ticketN: 7069,
    createdBy: 'user4',
    summary: 'Folder Access',
    descr: ['"Can you please give Abby access to the folder ‰ÛÏFY17 NIRCRESFEE‰Û that is under my personal drive?',
    'If you have any questions, please let me know.',
    'Thanks- Haley',
    'Haley Swartz',
    'Accountant II',
    'Recreational Services',
    '785-532-4948"',
    ],
    status: 'closed',
    category: 'Software - Other',
    department: 'REC',
    assign: 'James Barnes',
    createDate: '2016-07-01 @ 10:03 AM',
    closeDate: '2016-07-12 @ 12:19 PM',
    priority: 'Med'
  }
];

